substitutions:
  name: meridian-esp32
  fname: Meridian 561
  manufacture: Meridian Audio Ltd
  device_description: Digital Surround Controller
  version: 1.0.0
  rxpin: GPIO16
  txpin: GPIO17
  irpin: GPIO14

esphome:
  name: ${name}
  friendly_name: ${fname}
  project:
    name: ${manufacture}.${device_description}
    version: ${version}
  on_boot:
    priority: -100
    then:
      - delay: 2s
      - uart.write: "CS3\r"
esp32:
  board: esp32dev
  framework:
    type: arduino
api:
  encryption:
    key: !secret api
  on_client_connected:
    then:
      - lambda: |-
          id(uptime_s).publish_state(id(uptime_s).state);
      - lambda: |-
          id(uptime2).publish_state(id(uptime2).state);
ota:
  - platform: esphome
    password: !secret ota
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Meridian-Esp32"
    password: "3xhTvZS0Rcar"
captive_portal:
web_server:
  port: 80
  local: true

remote_receiver:
  pin:
    number: ${irpin}
    inverted: true
    mode: INPUT_PULLUP
  dump: rc6
  tolerance: 25%
  filter: 4us
  idle: 10ms

uart:
  - id: uart_2
    tx_pin: ${txpin}  # TX пин ESP
    rx_pin: ${rxpin}  # RX пин ESP
    baud_rate: 9600
    stop_bits: 1
    parity: NONE
    # Триггер на получение строки, заканчивающейся на \n
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\r"  # Делимитер \r
      sequence:
        - lambda: |-
            UARTDebug::log_string(direction, bytes);
            std::string str(bytes.begin(), bytes.end());
            std::replace(str.begin(), str.end(), 'O', '0');
            id(uart_raw_data).publish_state(str);
            if (str == "         .  \r") {
              id(meridian_standby_status).publish_state(false);  // OFF
            } else {
              id(meridian_standby_status).publish_state(true);   // ON
            }
            if (str.length() == 13) {
              std::string volume_str = str.substr(10, 2);
              std::string source_code = str.substr(0, 10);
              std::map<std::string, std::string> source_map = {
                {"CD        ", "CD"},
                {"Radio     ", "Radio"},
                {"DTV       ", "DTV"},
                {"TV        ", "TV"},
                {"Tape1     ", "Tape 1"},
                {"Tape2     ", "Tape 2"},
                {"CDR       ", "CDR"},
                {"Cable     ", "Cable"},
                {"DVD       ", "DVD"},
                {"VCR1      ", "VCR1"},
                {"VCR2      ", "VCR2"},
                {"LDisc     ", "Laser Disc"},
                {"Ldisc     ", "Laser Disc"}
              };
              auto it = source_map.find(source_code);
              if (it != source_map.end()) {
                std::string selected_source = it->second;
                id(mode).publish_state(selected_source);
              } else {
                
              }
              if (std::all_of(volume_str.begin(), volume_str.end(), ::isdigit)) {
                int volume = std::stoi(volume_str);
                if (volume >= 1 && volume <= 99) {
                  id(volume_control).publish_state(volume);
                  str[10] = '0' + (volume / 10);
                  str[11] = '0' + (volume % 10);
                } else {
                }
              } else {
                
              }
            }
logger:
button:
  - platform: template
    name: "Meridian Standby"
    on_press:
      - if:
          condition:
            binary_sensor.is_on: meridian_standby_status
          then:
            - uart.write: "SB\r"
            - delay: 2s
            - uart.write: "CS3\r"
          else:
            - uart.write: !lambda |-
                std::map<std::string, std::vector<uint8_t>> mode_commands = {
                  {"CD", {0x43, 0x44, 0x0D}},      // "CD\r"
                  {"Radio", {0x52, 0x44, 0x0D}},   // "RD\r"
                  {"DTV", {0x44, 0x54, 0x0D}},     // "DT\r"
                  {"TV", {0x54, 0x56, 0x0D}},      // "TV\r"
                  {"Tape 1", {0x54, 0x31, 0x0D}},   // "T1\r"
                  {"Tape 2", {0x54, 0x32, 0x0D}},   // "T2\r"
                  {"CDR", {0x43, 0x52, 0x0D}},     // "CR\r"
                  {"Cable", {0x43, 0x42, 0x0D}},   // "CB\r"
                  {"DVD", {0x44, 0x56, 0x0D}},     // "DV\r"
                  {"VCR1", {0x56, 0x31, 0x0D}},    // "V1\r"
                  {"VCR2", {0x56, 0x32, 0x0D}},    // "V2\r"
                  {"Laser Disc", {0x4C, 0x44, 0x0D}} // "LD\r"
                };
                auto command = mode_commands.find(id(mode).state);
                if (command != mode_commands.end()) {
                  return command->second;
                }
                return std::vector<uint8_t>{};
#      - delay: 2s
  - platform: template
    name: "Meridian Volume Up"
    on_press:
      - uart.write: "VP\r"
  - platform: template
    name: "Meridian Volume Down"
    on_press:
      - uart.write: "VM\r"
  - platform: template
    name: "Mute"
    on_press:
      - uart.write: "MU\r"

interval:
  - interval: 60s
    then:
      - uart.write: "CS3\r"


select:
  - platform: template
    name: "Meridian Source"
    id: mode
    options:
      - "CD"
      - "Radio"
      - "DTV"
      - "TV"
      - "Tape 1"
      - "Tape 2"
      - "CDR"
      - "Cable"
      - "DVD"
      - "VCR1"
      - "VCR2"
      - "Laser Disc"
    initial_option: "CD"
    optimistic: true
    set_action:
      - uart.write: !lambda |-
          std::map<std::string, std::vector<uint8_t>> mode_commands = {
            {"CD", {0x43, 0x44, 0x0D}},      // "CD\r"
            {"Radio", {0x52, 0x44, 0x0D}},   // "RD\r"
            {"DTV", {0x44, 0x54, 0x0D}},     // "DT\r"
            {"TV", {0x54, 0x56, 0x0D}},      // "TV\r"
            {"Tape 1", {0x54, 0x31, 0x0D}},   // "T1\r"
            {"Tape 2", {0x54, 0x32, 0x0D}},   // "T2\r"
            {"CDR", {0x43, 0x52, 0x0D}},     // "CR\r"
            {"Cable", {0x43, 0x42, 0x0D}},   // "CB\r"
            {"DVD", {0x44, 0x56, 0x0D}},     // "DV\r"
            {"VCR1", {0x56, 0x31, 0x0D}},    // "V1\r"
            {"VCR2", {0x56, 0x32, 0x0D}},    // "V2\r"
            {"Laser Disc", {0x4C, 0x44, 0x0D}} // "LD\r"
          };
          auto command = mode_commands.find(x);
          if (command != mode_commands.end()) {
            return command->second;
          }
          return std::vector<uint8_t>{};
number:
  - platform: template
    name: "Volume Control"
    id: volume_control
    min_value: 1
    max_value: 99
    step: 1
    initial_value: 50
    set_action:
      - uart.write: !lambda |-
          int volume = (int)x;
          std::string command = "VN";
          if (volume < 10) {
            command += "0"; 
          }
          command += std::to_string(volume) + "\r";
          std::vector<uint8_t> byte_command;
          for (char c : command) {
            byte_command.push_back(static_cast<uint8_t>(c));
          }
          return byte_command;

switch:
  - platform: template
    name: "IR Only for Laser Disc"
    id: ir_only_tape1
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: remote_receiver
    name: "Volume Up IR"
    rc6:
      address: 0x10
      command: 0x10
    on_press:
      then:
        - if:
            condition:
              or:
                - not:
                    switch.is_on: ir_only_tape1
                - lambda: 'return id(mode).state == "Laser Disc";'
            then:
              - uart.write: "VP\r"

  - platform: remote_receiver
    name: "Volume Down IR"
    rc6:
      address: 0x10
      command: 0x11
    on_press:
      then:
        - if:
            condition:
              or:
                - not:
                    switch.is_on: ir_only_tape1
                - lambda: 'return id(mode).state == "Laser Disc";'
            then:
              - uart.write: "VM\r"
  - platform: template
    name: "Meridian Standby Status"
    id: meridian_standby_status
    device_class: power

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy 
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: "diagnostic"
    device_class: ""
  - platform: uptime
    name: "Uptime s"
    id: uptime_s
    update_interval: 60s
text_sensor:
  - platform: template
    name: "Uptime"
    id: uptime2
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 60s
  - platform: template
    name: "UART Raw Data"
    id: uart_raw_data
